# fly.toml app configuration file generated for glimpseguru-tracker on 2024-01-21T23:32:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "glimpseguru-tracker"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
